"""Declarative, idempotent tenant onboarding (Phase 1P.3).

This package turns a declarative tenant manifest into an explicit, reviewable
plan and applies it to the control plane. It deliberately owns no HTTP surface:
it is the shared engine behind ``scripts/onboard_tenant.py`` and the tests.

Design rules that the rest of the phase depends on:

* The tenant slug is the existing ``organizations.external_id`` column (unique,
  nullable, 100 chars). No migration is introduced to hold a second identifier.
* A manifest never contains a secret. Widget keys are generated by the tool and
  printed at most once; credentials, connection strings, and staff tokens are
  rejected at load time rather than logged.
* Planning is pure with respect to the database: a plan can be computed, shown,
  and discarded without a write. Application re-checks every precondition inside
  the transaction, so a stale plan fails loudly instead of corrupting a tenant.
* Every write is tenant-scoped by construction. Nothing in this package accepts a
  caller-supplied organization id.
"""

from app.tenant_onboarding.manifest import (
    ManifestError,
    TenantManifest,
    load_manifest_file,
    parse_manifest,
)
from app.tenant_onboarding.planner import (
    OnboardingAction,
    OnboardingConflictError,
    OnboardingPlan,
    OnboardingResult,
    apply_plan,
    build_embed_snippet,
    build_plan,
    generate_public_widget_key,
    list_tenant_widget_keys_status,
    resolve_canonical_public_chat_config,
)

__all__ = [
    "ManifestError",
    "OnboardingAction",
    "OnboardingConflictError",
    "OnboardingPlan",
    "OnboardingResult",
    "TenantManifest",
    "apply_plan",
    "build_embed_snippet",
    "build_plan",
    "generate_public_widget_key",
    "list_tenant_widget_keys_status",
    "load_manifest_file",
    "parse_manifest",
    "resolve_canonical_public_chat_config",
]
