"""add integration job queue

Revision ID: 075bb6e47d9b
Revises: 29800ec281a4
Create Date: 2026-08-17 12:19:26.339148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '075bb6e47d9b'
down_revision: Union[str, Sequence[str], None] = '29800ec281a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_jobs_dedupe_key'), 'integration_jobs', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_integration_jobs_job_type'), 'integration_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_integration_jobs_status'), 'integration_jobs', ['status'], unique=False)
    op.add_column("ticket_events",sa.Column("writeback_completed",sa.Boolean(),server_default=sa.text("false"),nullable=False,),
    )
    op.alter_column("ticket_events","writeback_completed",server_default=None,)

    op.add_column('ticket_events', sa.Column('writeback_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticket_events', 'writeback_at')
    op.drop_column('ticket_events', 'writeback_completed')
    op.drop_index(op.f('ix_integration_jobs_status'), table_name='integration_jobs')
    op.drop_index(op.f('ix_integration_jobs_job_type'), table_name='integration_jobs')
    op.drop_index(op.f('ix_integration_jobs_dedupe_key'), table_name='integration_jobs')
    op.drop_table('integration_jobs')
    # ### end Alembic commands ###
