"""add customer_identities

Revision ID: 1e4a0001
Revises: 1e3a0001
Create Date: 2026-09-19 17:07:10.246523

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1e4a0001'
down_revision: str | Sequence[str] | None = '1e3a0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_identities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('identity_type', sa.String(length=50), nullable=False),
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('normalized_identifier', sa.String(length=255), nullable=False),
    sa.Column(
        'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.Column(
        'updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
    ),
    sa.ForeignKeyConstraint(
        ['customer_id', 'organization_id'],
        ['customers.id', 'customers.organization_id'],
        name='fk_customer_identities_customer_organization',
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'organization_id',
        'provider',
        'identity_type',
        'normalized_identifier',
        name='ux_customer_identities_tenant_provider_identity',
    )
    )
    op.create_index(
        'ix_customer_identities_customer_id',
        'customer_identities',
        ['customer_id'],
        unique=False,
    )
    op.create_index(
        'ix_customer_identities_organization_id',
        'customer_identities',
        ['organization_id'],
        unique=False,
    )
    op.create_index(
        'ix_customer_identities_provider_lookup',
        'customer_identities',
        ['organization_id', 'provider', 'identity_type', 'normalized_identifier'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customer_identities_provider_lookup', table_name='customer_identities')
    op.drop_index('ix_customer_identities_organization_id', table_name='customer_identities')
    op.drop_index('ix_customer_identities_customer_id', table_name='customer_identities')
    op.drop_table('customer_identities')
    # ### end Alembic commands ###
