"""add conversations and conversation messages

Revision ID: 1f0a0001
Revises: 1e4a0001
Create Date: 2026-09-19 21:18:36.516246

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1f0a0001'
down_revision: str | Sequence[str] | None = '1e4a0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('external_thread_id', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latest_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.Column(
        'updated_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(
        ['customer_id', 'organization_id'],
        ['customers.id', 'customers.organization_id'],
        name='fk_conversations_customer_organization_customers',
        ondelete='CASCADE',
    ),
    # The plain organization FK is separate from the composite tenant-safe
    # customer/ticket links; a composite FK renders only its own columns.
    sa.ForeignKeyConstraint(
        ['organization_id'],
        ['organizations.id'],
    ),
    sa.ForeignKeyConstraint(
        ['ticket_id', 'organization_id'],
        ['tickets.id', 'tickets.organization_id'],
        name='fk_conversations_ticket_organization_tickets',
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'id', 'organization_id', name='ux_conversations_id_organization_id'
    ),
    sa.UniqueConstraint(
        'organization_id',
        'provider',
        'external_thread_id',
        name='ux_conversations_tenant_provider_thread',
    ),
    )
    op.create_index(
        'ix_conversations_customer_id', 'conversations', ['customer_id'], unique=False
    )
    op.create_index(
        'ix_conversations_organization_id',
        'conversations',
        ['organization_id'],
        unique=False,
    )
    op.create_index(
        'ix_conversations_ticket_id', 'conversations', ['ticket_id'], unique=False
    )
    op.create_table('conversation_messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_message_id', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column(
        'created_at',
        sa.DateTime(timezone=True),
        server_default=sa.text('now()'),
        nullable=False,
    ),
    sa.ForeignKeyConstraint(
        ['conversation_id', 'organization_id'],
        ['conversations.id', 'conversations.organization_id'],
        name='fk_conversation_messages_conversation_organization',
        ondelete='CASCADE',
    ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        'conversation_id',
        'dedupe_key',
        name='ux_conversation_messages_conversation_dedupe',
    ),
    sa.UniqueConstraint(
        'id', 'organization_id', name='ux_conversation_messages_id_organization_id'
    ),
    sa.UniqueConstraint(
        'organization_id',
        'provider',
        'external_message_id',
        name='ux_conversation_messages_tenant_provider_external',
    ),
    )
    op.create_index(
        'ix_conversation_messages_conversation_id',
        'conversation_messages',
        ['conversation_id'],
        unique=False,
    )
    op.create_index(
        'ix_conversation_messages_conversation_sent_at',
        'conversation_messages',
        ['conversation_id', 'sent_at'],
        unique=False,
    )
    op.create_index(
        'ix_conversation_messages_organization_id',
        'conversation_messages',
        ['organization_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        'ix_conversation_messages_organization_id',
        table_name='conversation_messages',
    )
    op.drop_index(
        'ix_conversation_messages_conversation_sent_at',
        table_name='conversation_messages',
    )
    op.drop_index(
        'ix_conversation_messages_conversation_id',
        table_name='conversation_messages',
    )
    op.drop_table('conversation_messages')
    op.drop_index(
        'ix_conversations_ticket_id', table_name='conversations'
    )
    op.drop_index(
        'ix_conversations_organization_id', table_name='conversations'
    )
    op.drop_index(
        'ix_conversations_customer_id', table_name='conversations'
    )
    op.drop_table('conversations')
    # ### end Alembic commands ###