"""add AI request observability

Revision ID: 9333562cd6ec
Revises: ceec6d2a6a89
Create Date: 2026-08-18 06:26:55.429890

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9333562cd6ec"
down_revision: str | Sequence[str] | None = "ceec6d2a6a89"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_request_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("feature", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("answer", sa.Text(), nullable=True),
        sa.Column("grounded", sa.Boolean(), nullable=False),
        sa.Column("llm_called", sa.Boolean(), nullable=False),
        sa.Column("retrieval_count", sa.Integer(), nullable=False),
        sa.Column("best_similarity", sa.Float(), nullable=True),
        sa.Column("input_tokens", sa.Integer(), nullable=False),
        sa.Column("output_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Float(), nullable=False),
        sa.Column("latency_ms", sa.Float(), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_request_logs_feature"), "ai_request_logs", ["feature"], unique=False
    )
    op.create_index(
        op.f("ix_ai_request_logs_request_id"),
        "ai_request_logs",
        ["request_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_ai_request_logs_status"), "ai_request_logs", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_request_logs_status"), table_name="ai_request_logs")
    op.drop_index(op.f("ix_ai_request_logs_request_id"), table_name="ai_request_logs")
    op.drop_index(op.f("ix_ai_request_logs_feature"), table_name="ai_request_logs")
    op.drop_table("ai_request_logs")
    # ### end Alembic commands ###
