"""add ticket routing fields

Revision ID: cfd495521e21
Revises: 5e006c1a3fe5
Create Date: 2026-08-16 07:35:13.613079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfd495521e21'
down_revision: Union[str, Sequence[str], None] = '5e006c1a3fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('tickets', sa.Column('assigned_team', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'assigned_team')
    op.drop_column('tickets', 'category')
    # ### end Alembic commands ###
